"""delete access

Revision ID: 3274b31d3541
Revises: 12f1234eac67
Create Date: 2026-02-03 20:20:35.889101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3274b31d3541"
down_revision: Union[str, Sequence[str], None] = "12f1234eac67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("time", sa.DateTime(), nullable=False))
    op.drop_column("users", "access")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("access", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_column("messages", "time")
    # ### end Alembic commands ###
