"""add the new column - chat_id

Revision ID: b6113bf67e77
Revises: 3274b31d3541
Create Date: 2026-02-03 20:36:30.588918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b6113bf67e77"
down_revision: Union[str, Sequence[str], None] = "3274b31d3541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("chat_id", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "chat_id")
    # ### end Alembic commands ###
