"""the new table - stopwords

Revision ID: ea7de4c4b99f
Revises: a4bc8824d6e9
Create Date: 2026-02-08 02:30:11.471066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ea7de4c4b99f"
down_revision: Union[str, Sequence[str], None] = "a4bc8824d6e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stopwords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stopwords")
    # ### end Alembic commands ###
